import Head from 'next/head'
import WorldMap from '../components/maps'
export default function Home() {
  return (
    <div>
      <Head>
        <title>Country Maps</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>

      <main >
        <h1>
        Maps Example
        </h1>   
        <WorldMap/>   
      </main>

    </div>
  )
}
